################ English language ##################
# [en]
# languageName = "English"
# languageCode = "en-us"
# contentDir = "content/english"
# weight = 1

[zh]
languageName = "中文"
languageCode = "zh-tw"
contentDir = "content/zh-tw"
weight = 2
