################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[zh]
languageName = "Zh"
languageCode = "zh-tw"
contentDir = "content/zh-tw"
weight = 2
