############# English navigation ##############

# main menu
[[main]]
name = "首頁"
url = "/"
weight = 1

[[main]]
name = "新聞"
url = "/news"
weight = 4

[[main]]
name = "關於我們"
url = "/about"
weight = 6


# footer menu
[[footer]]
name = "關於我們"
url = "/about"
weight = 1

[[footer]]
name = "隱私政策"
url = "/privacy-policy"
weight = 3
