############# English navigation ##############

# main menu
[[main]]
name = "首頁"
url = "/"
weight = 1


[[main]]
name = "Contact"
url = "/contact"
weight = 4

[[main]]
name = "Authors"
url = "/authors"
weight = 5

[[main]]
name = "About"
url = "/about"
weight = 6

[[main]]
name = "News"
url = "/news"
weight = 7


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
