############# English navigation ##############

# main menu
[[main]]
name = "首頁"
url = "/"
weight = 1

[[main]]
name = "最新消息"
url = "/news"
weight = 2

[[main]]
name = "SpectraSense技術"
url = "/spectra-sense"
weight = 3

[[main]]
name = "InsightModel技術"
url = "/insight-model"
weight = 4

[[main]]
name = "產品"
url = "/404"
weight = 5

[[main]]
name = "解決方案"
url = "/404"
weight = 6

[[main]]
name = "關於我們"
url = "/404"
weight = 7


# footer menu
[[footer]]
name = "技術"
weight = 1
hasChildren = true

[[footer]]
name = "SpectraSense"
parent = "技術"
url = "/spectra-sense"
weight = 1

[[footer]]
name = "InsightModel"
parent = "技術"
url = "/insight-model"
weight = 2

[[footer]]
name = "產品"
weight = 2
hasChildren = true

[[footer]]
name = "SpectraSense Ultra"
parent = "產品"
url = "/404"
weight = 1

[[footer]]
name = "SpectraSense Pro"
parent = "產品"
url = "/404"
weight = 2

[[footer]]
name = "SpectraSense Lite"
parent = "產品"
url = "/404"
weight = 3

[[footer]]
name = "InsightHub"
parent = "產品"
url = "/404"
weight = 4

[[footer]]
name = "解決方案"
weight = 3
hasChildren = true

[[footer]]
name = "工業檢測"
parent = "解決方案"
url = "/404"
weight = 1

[[footer]]
name = "關於洸研"
weight = 4
hasChildren = true

[[footer]]
name = "關於我們"
parent = "關於洸研"
url = "/404"
weight = 1

[[footer]]
name = "最新消息"
parent = "關於洸研"
url = "/news"
weight = 2

[[footer]]
name = "隱私權政策"
parent = "關於洸研"
url = "/404"
weight = 3

[[footer]]
name = "人才招募"
parent = "關於洸研"
url = "/404"
weight = 4

[[footer]]
name = "聯絡我們"
parent = "關於洸研"
url = "/404"
weight = 5
